import { cloudflare } from "@cloudflare/vite-plugin";
import { cloudflareTest, readD1Migrations } from "@cloudflare/vitest-plugin";
import react from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";

/**
 * The Cloudflare plugin must not load under Vitest.
 *
 * vite-plus injects `resolve.external` (every Node builtin) into all
 * environments, and @cloudflare/vite-plugin hard-rejects that on Worker
 * environments — so `vp test` dies at config resolution. It is also redundant
 * there: the "workers" project below gets its workerd runtime from
 * cloudflareTest() instead. Dev and build are unaffected.
 */
const isVitest = process.env["VITEST"] !== undefined;

export default defineConfig({
  // lazyPlugins keeps these from being constructed when vp only loads this file
  // to read the lint/fmt/test metadata blocks below.
  plugins: lazyPlugins(() => [
    // Native Oxc React Compiler (oxc-transform-react). Vite marks this
    // experimental; the stable fallback is:
    //   react(), babel({ presets: [reactCompilerPreset()] })
    // via @rolldown/plugin-babel + babel-plugin-react-compiler.
    react({ compiler: true }),
    ...(isVitest ? [] : [cloudflare()]),
  ]),

  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    ignorePatterns: [
      ".agents/**",
      ".claude/**",
      "dist/**",
      // Generated by `wrangler types` and `drizzle-kit generate` — reformatting
      // them just creates churn on every regeneration.
      "worker-configuration.d.ts",
      "drizzle/**",
    ],
  },
  lint: {
    ignorePatterns: [
      ".agents/**",
      ".claude/**",
      "dist/**",
      "worker-configuration.d.ts",
      "drizzle/**",
    ],
    plugins: ["react", "react-perf", "jsx-a11y", "promise", "import"],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },

  test: {
    projects: [
      {
        // Pure logic: Zod schemas and Hono routes exercised via app.request().
        // No Workers runtime needed, so these stay fast.
        test: {
          name: "node",
          environment: "node",
          include: ["src/**/*.test.ts", "worker/**/*.test.ts", "shared/**/*.test.ts"],
          // *.workers.test.ts belongs to the workers project below; without this
          // the node project also matches it and fails on `cloudflare:test`.
          exclude: ["**/*.workers.test.ts"],
        },
      },
      {
        // Anything touching a real binding (D1) runs inside workerd.
        plugins: [
          cloudflareTest(async () => ({
            wrangler: { configPath: "./wrangler.jsonc" },
            miniflare: {
              // Handed to the setup file, which applies them before each suite
              // so every test file starts from a migrated, empty database.
              bindings: {
                TEST_MIGRATIONS: await readD1Migrations("./drizzle/migrations"),
              },
            },
          })),
        ],
        test: {
          name: "workers",
          include: ["worker/**/*.workers.test.ts"],
          setupFiles: ["./worker/test/apply-migrations.ts"],
        },
      },
    ],
  },
});
