import { zValidator } from "@hono/zod-validator";
import { createGateway, createUIMessageStream, createUIMessageStreamResponse } from "ai";
import { Hono } from "hono";
import { cors } from "hono/cors";

import {
  PASSWORD_QUERY_PARAM,
  REALTIME_TOKEN_TTL_SECONDS,
  REALTIME_TOOLS,
  VOICE_MODEL_ID,
} from "../shared/realtime.ts";
import { PasswordSchema, RealtimeSetupSchema, ViewRequestSchema } from "../shared/schemas.ts";
import type { ViewUIMessage } from "../shared/view.ts";
import { buildView, viewModel } from "./view-agent.ts";

/**
 * `CloudflareBindings` (not `Env`) is generated by
 * `wrangler types --env-interface CloudflareBindings`. The explicit name avoids
 * colliding with Hono's own `Env` type.
 */
type AppEnv = { Bindings: CloudflareBindings };

/**
 * Origins the Capacitor WebView uses once the app is bundled natively.
 * iOS serves from capacitor://localhost, Android from https://localhost.
 */
const NATIVE_ORIGINS = ["capacitor://localhost", "http://localhost", "https://localhost"];

/**
 * Constant-time string compare so a shared password cannot be recovered a
 * character at a time. `crypto.subtle.timingSafeEqual` is Workers-only and
 * would not run in the node test project, so this stays portable.
 */
function passwordMatches(candidate: string, expected: string): boolean {
  if (expected.length === 0 || candidate.length !== expected.length) return false;

  let difference = 0;
  for (let index = 0; index < candidate.length; index += 1) {
    difference |= candidate.charCodeAt(index) ^ expected.charCodeAt(index);
  }
  return difference === 0;
}

/**
 * Routes MUST stay chained. Breaking the chain into separate `api.get(...)`
 * statements silently destroys RPC type inference — the client still compiles,
 * it just degrades to `any`.
 */
const api = new Hono<AppEnv>()
  .get("/health", (c) => c.json({ ok: true } as const))

  /** Lets the UI check the password before it opens a billable session. */
  .post("/auth", zValidator("json", PasswordSchema), (c) => {
    const { password } = c.req.valid("json");
    if (!passwordMatches(password, c.env.APP_PASSWORD)) {
      return c.json({ error: "Wrong password" }, 401);
    }
    return c.json({ ok: true } as const);
  })

  /**
   * Mints a short-lived AI Gateway client secret. The browser never sees the
   * Gateway key; it gets a `vcst_` token that expires in a minute.
   *
   * The password rides in the query string because `experimental_useRealtime`
   * owns this fetch and sends no custom headers.
   */
  .post("/realtime/setup", async (c) => {
    if (!passwordMatches(c.req.query(PASSWORD_QUERY_PARAM) ?? "", c.env.APP_PASSWORD)) {
      return c.json({ error: "Wrong password" }, 401);
    }

    const apiKey = c.env.AI_GATEWAY_API_KEY;
    if (!apiKey) {
      return c.json({ error: "AI_GATEWAY_API_KEY is not configured on this Worker" }, 500);
    }

    const gateway = createGateway({ apiKey });

    try {
      const token = await gateway.experimental_realtime.getToken({
        model: VOICE_MODEL_ID,
        expiresAfterSeconds: REALTIME_TOKEN_TTL_SECONDS,
      });

      const setup = RealtimeSetupSchema.safeParse(token);
      if (!setup.success) {
        return c.json({ error: "The Gateway returned an unusable realtime token" }, 502);
      }

      /**
       * `tools` is ours, not the Gateway's — `getToken()` only mints a secret.
       * The hook reads the tool list off this response and puts it in the
       * `session-update` it sends when the socket opens, so a tool declared
       * anywhere else in the app would never reach the model.
       */
      return c.json({ ...setup.data, tools: REALTIME_TOOLS });
    } catch (error) {
      return c.json(
        { error: error instanceof Error ? error.message : "Realtime setup failed" },
        502,
      );
    }
  })

  /**
   * Runs the coding agent and streams it back as a UI message stream.
   *
   * It streams because the caller is a voice conversation: the browser answers
   * the model's tool call immediately and then has ten or twenty seconds to
   * account for, and a silent request is indistinguishable from a dead one.
   * `data-progress` is transient — status, not history — and `data-view` is the
   * finished document.
   */
  .post("/view", zValidator("json", ViewRequestSchema), (c) => {
    const { password, request, currentHtml } = c.req.valid("json");

    if (!passwordMatches(password, c.env.APP_PASSWORD)) {
      return c.json({ error: "Wrong password" }, 401);
    }

    const apiKey = c.env.AI_GATEWAY_API_KEY;
    if (!apiKey) {
      return c.json({ error: "AI_GATEWAY_API_KEY is not configured on this Worker" }, 500);
    }

    const stream = createUIMessageStream<ViewUIMessage>({
      execute: async ({ writer }) => {
        const view = await buildView({
          model: viewModel(apiKey),
          request,
          currentHtml,
          onProgress: (progress) =>
            writer.write({ type: "data-progress", data: progress, transient: true }),
        });

        writer.write({ type: "data-view", data: view });
      },
      /**
       * Returned to the browser as an error part instead of a dropped
       * connection — by the time the agent can fail, the response has already
       * begun, so a status code is no longer available.
       */
      onError: (error) => (error instanceof Error ? error.message : "The coding agent failed."),
    });

    return createUIMessageStreamResponse({ stream });
  });

const app = new Hono<AppEnv>().use("/api/*", cors({ origin: NATIVE_ORIGINS })).route("/api", api);

export type AppType = typeof app;

export default app;
