import { zValidator } from "@hono/zod-validator";
import { desc, eq } from "drizzle-orm";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { z } from "zod";

import { CreateItemSchema, UpdateItemSchema } from "../shared/schemas.ts";
import { createDb } from "./db/client.ts";
import { items } from "./db/schema.ts";

/**
 * `CloudflareBindings` (not `Env`) is generated by
 * `wrangler types --env-interface CloudflareBindings`. The explicit name avoids
 * colliding with Hono's own `Env` type.
 */
type AppEnv = { Bindings: CloudflareBindings };

const IdParamSchema = z.object({ id: z.uuid() });

/**
 * Origins the Capacitor WebView uses once the app is bundled natively.
 * iOS serves from capacitor://localhost, Android from https://localhost.
 */
const NATIVE_ORIGINS = ["capacitor://localhost", "http://localhost", "https://localhost"];

/**
 * Routes MUST stay chained. Breaking the chain into separate `api.get(...)`
 * statements silently destroys RPC type inference — the client still compiles,
 * it just degrades to `any`.
 */
const api = new Hono<AppEnv>()
  .get("/health", (c) => c.json({ ok: true } as const))

  .get("/items", async (c) => {
    const db = createDb(c.env.DB);
    const rows = await db.select().from(items).orderBy(desc(items.createdAt));
    return c.json({
      items: rows.map((row) => ({
        ...row,
        createdAt: row.createdAt.getTime(),
      })),
    });
  })

  .post("/items", zValidator("json", CreateItemSchema), async (c) => {
    const { title } = c.req.valid("json");
    const db = createDb(c.env.DB);
    const [row] = await db.insert(items).values({ title }).returning();
    if (!row) return c.json({ error: "Insert failed" }, 500);
    return c.json({ item: { ...row, createdAt: row.createdAt.getTime() } }, 201);
  })

  .patch(
    "/items/:id",
    zValidator("param", IdParamSchema),
    zValidator("json", UpdateItemSchema),
    async (c) => {
      const { id } = c.req.valid("param");
      const { done } = c.req.valid("json");
      const db = createDb(c.env.DB);
      const [row] = await db.update(items).set({ done }).where(eq(items.id, id)).returning();
      if (!row) return c.json({ error: "Not found" }, 404);
      return c.json({ item: { ...row, createdAt: row.createdAt.getTime() } });
    },
  )

  .delete("/items/:id", zValidator("param", IdParamSchema), async (c) => {
    const { id } = c.req.valid("param");
    const db = createDb(c.env.DB);
    await db.delete(items).where(eq(items.id, id));
    return c.body(null, 204);
  });

const app = new Hono<AppEnv>().use("/api/*", cors({ origin: NATIVE_ORIGINS })).route("/api", api);

export type AppType = typeof app;

export default app;
