import { zValidator } from "@hono/zod-validator";
import { createGateway } from "ai";
import { Hono } from "hono";
import { cors } from "hono/cors";

import {
  PASSWORD_QUERY_PARAM,
  REALTIME_TOKEN_TTL_SECONDS,
  VOICE_MODEL_ID,
} from "../shared/realtime.ts";
import { PasswordSchema, RealtimeSetupSchema } from "../shared/schemas.ts";

/**
 * `CloudflareBindings` (not `Env`) is generated by
 * `wrangler types --env-interface CloudflareBindings`. The explicit name avoids
 * colliding with Hono's own `Env` type.
 */
type AppEnv = { Bindings: CloudflareBindings };

/**
 * Origins the Capacitor WebView uses once the app is bundled natively.
 * iOS serves from capacitor://localhost, Android from https://localhost.
 */
const NATIVE_ORIGINS = ["capacitor://localhost", "http://localhost", "https://localhost"];

/**
 * Constant-time string compare so a shared password cannot be recovered a
 * character at a time. `crypto.subtle.timingSafeEqual` is Workers-only and
 * would not run in the node test project, so this stays portable.
 */
function passwordMatches(candidate: string, expected: string): boolean {
  if (expected.length === 0 || candidate.length !== expected.length) return false;

  let difference = 0;
  for (let index = 0; index < candidate.length; index += 1) {
    difference |= candidate.charCodeAt(index) ^ expected.charCodeAt(index);
  }
  return difference === 0;
}

/**
 * Routes MUST stay chained. Breaking the chain into separate `api.get(...)`
 * statements silently destroys RPC type inference — the client still compiles,
 * it just degrades to `any`.
 */
const api = new Hono<AppEnv>()
  .get("/health", (c) => c.json({ ok: true } as const))

  /** Lets the UI check the password before it opens a billable session. */
  .post("/auth", zValidator("json", PasswordSchema), (c) => {
    const { password } = c.req.valid("json");
    if (!passwordMatches(password, c.env.APP_PASSWORD)) {
      return c.json({ error: "Wrong password" }, 401);
    }
    return c.json({ ok: true } as const);
  })

  /**
   * Mints a short-lived AI Gateway client secret. The browser never sees the
   * Gateway key; it gets a `vcst_` token that expires in a minute.
   *
   * The password rides in the query string because `experimental_useRealtime`
   * owns this fetch and sends no custom headers.
   */
  .post("/realtime/setup", async (c) => {
    if (!passwordMatches(c.req.query(PASSWORD_QUERY_PARAM) ?? "", c.env.APP_PASSWORD)) {
      return c.json({ error: "Wrong password" }, 401);
    }

    const apiKey = c.env.AI_GATEWAY_API_KEY;
    if (!apiKey) {
      return c.json({ error: "AI_GATEWAY_API_KEY is not configured on this Worker" }, 500);
    }

    const gateway = createGateway({ apiKey });

    try {
      const token = await gateway.experimental_realtime.getToken({
        model: VOICE_MODEL_ID,
        expiresAfterSeconds: REALTIME_TOKEN_TTL_SECONDS,
      });

      const setup = RealtimeSetupSchema.safeParse(token);
      if (!setup.success) {
        return c.json({ error: "The Gateway returned an unusable realtime token" }, 502);
      }

      return c.json(setup.data);
    } catch (error) {
      return c.json(
        { error: error instanceof Error ? error.message : "Realtime setup failed" },
        502,
      );
    }
  });

const app = new Hono<AppEnv>().use("/api/*", cors({ origin: NATIVE_ORIGINS })).route("/api", api);

export type AppType = typeof app;

export default app;
